name: Update Crypto Data

on:
  schedule:
    # Run fetch_and_analyze.py every 30 minutes
    - cron: "*/30 * * * *"
    # Run sentiment_rss.py once per day at 6 AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch:  # allows manual trigger

jobs:
  update-crypto-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_and_analyze.py (every 30 min)
        if: github.event.schedule == '*/30 * * * *'
        run: python fetch_and_analyze.py

      - name: Run sentiment_rss.py (once per day)
        if: github.event.schedule == '0 6 * * *'
        run: python sentiment_rss.py

      - name: Commit and push updated data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto update crypto data [$(date)]" || echo "No changes to commit"
          git push
